language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10
  - 11
  - 12
notifications:
  email:
    recipients:
      - $GH_EMAIL
    on_success: change
    on_failure: always
install:
  - npm install

script:
  - npm run build
  - npm run test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
